export const orderStatus = {
CONFIRMED: 'CONFIRMED',
DEPOSIT_PAID : 'DEPOSIT_PAID',
BOOKED : 'BOOKED',
FULL_PAYMENT : "FULL_PAYMENT",
INVOICE_READY : 'INVOICE_READY',
PAKINGLIST_READY : 'PAKINGLIST_READY',
DONE_DEAL : 'DONE_DEAL',
}


